CREATE TABLE IF NOT EXISTS raw.ingestion_batch (
 batch_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_file_name VARCHAR(255) NOT NULL,
 source_file_sha256 CHAR(64) NOT NULL, source_system VARCHAR(255) NOT NULL,
 loaded_at_ts TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), row_count INT,
 status ENUM('started','loaded','failed') NOT NULL, error_message TEXT,
 INDEX idx_batch_checksum_status(source_file_sha256,status)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS raw.housing_listing (
 raw_row_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, batch_id BIGINT UNSIGNED NOT NULL,
 source_row_number INT NOT NULL, source_row_hash CHAR(32) NOT NULL,
 loaded_at_ts TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `listing_id` TEXT,
    `source` TEXT,
    `address` TEXT,
    `suburb` TEXT,
    `state` TEXT,
    `postcode` TEXT,
    `council_area` TEXT,
    `region` TEXT,
    `distance_to_cbd_km` TEXT,
    `lat` TEXT,
    `lon` TEXT,
    `property_type` TEXT,
    `bedrooms` TEXT,
    `bathrooms` TEXT,
    `car_spaces` TEXT,
    `toilets` TEXT,
    `land_size` TEXT,
    `building_area` TEXT,
    `year_built` TEXT,
    `has_pool` TEXT,
    `has_garage` TEXT,
    `sale_price` TEXT,
    `price_raw_aud` TEXT,
    `sale_date` TEXT,
    `sale_method` TEXT,
    `days_on_market` TEXT,
    `inspection_note` TEXT,
    `agent_name` TEXT,
    `agency_name` TEXT,
    `agent_phone` TEXT,
    `rba_cash_rate_pct` TEXT,
    `market_sentiment` TEXT,
    `market_context` TEXT,
    `suburb_median_price` TEXT,
    `auction_clearance_rate_pct` TEXT,
    `weekly_rent_aud` TEXT,
    `property_count_suburb` TEXT,
 UNIQUE KEY uq_raw_batch_row(batch_id,source_row_number),
 CONSTRAINT fk_raw_batch FOREIGN KEY(batch_id) REFERENCES raw.ingestion_batch(batch_id)
) ENGINE=InnoDB;
