INSERT INTO dw.dim_property_type(property_type_code,property_type_name,dwelling_group) VALUES ('house','House','Detached dwelling'),('unit_apartment','Unit / Apartment','Attached dwelling'),('townhouse','Townhouse','Attached dwelling'),('villa','Villa','Attached dwelling'),('duplex','Duplex','Semi-attached dwelling'),('land','Land','Vacant land'),('unknown','Unknown','Unknown') ON DUPLICATE KEY UPDATE property_type_name=VALUES(property_type_name),dwelling_group=VALUES(dwelling_group);
INSERT IGNORE INTO dw.dim_source(source_name) SELECT DISTINCT source_clean FROM stg.housing_ranked;
INSERT INTO dw.dim_geography(geography_natural_key,suburb_name,postcode,council_area,region_name,state_code,state_name)
SELECT geography_natural_key,MAX(suburb_clean),MAX(postcode_clean),MAX(council_area_clean),MAX(region_clean),state_code,CASE state_code WHEN 'NSW' THEN 'New South Wales' WHEN 'VIC' THEN 'Victoria' WHEN 'QLD' THEN 'Queensland' WHEN 'SA' THEN 'South Australia' WHEN 'WA' THEN 'Western Australia' WHEN 'TAS' THEN 'Tasmania' WHEN 'NT' THEN 'Northern Territory' WHEN 'ACT' THEN 'Australian Capital Territory' END FROM stg.housing_ranked WHERE state_code IS NOT NULL GROUP BY geography_natural_key,state_code
ON DUPLICATE KEY UPDATE suburb_name=VALUES(suburb_name),postcode=VALUES(postcode),council_area=VALUES(council_area),region_name=VALUES(region_name),state_code=VALUES(state_code),state_name=VALUES(state_name),updated_at_ts=CURRENT_TIMESTAMP(6);
DROP TEMPORARY TABLE IF EXISTS tmp_latest_agent;
CREATE TEMPORARY TABLE tmp_latest_agent AS SELECT * FROM (SELECT agent_natural_key,agent_name_clean,agency_name_clean,IF(is_phone_plausible AND CHAR_LENGTH(agent_phone_clean)>=4,CONCAT(REPEAT('*',GREATEST(CHAR_LENGTH(agent_phone_clean)-4,0)),RIGHT(agent_phone_clean,4)),NULL) agent_phone_masked,is_phone_plausible,sale_date_parsed effective_from_date,MD5(CONCAT_WS('|',COALESCE(agent_name_clean,''),COALESCE(agency_name_clean,''),COALESCE(agent_phone_clean,''))) source_attribute_hash,ROW_NUMBER() OVER(PARTITION BY agent_natural_key ORDER BY sale_date_parsed DESC,quality_score DESC,raw_row_id DESC) rn FROM stg.housing_ranked WHERE agent_natural_key IS NOT NULL AND sale_date_parsed IS NOT NULL) x WHERE rn=1;
UPDATE dw.dim_agent d JOIN tmp_latest_agent l ON l.agent_natural_key=d.agent_natural_key AND d.is_current=1 SET d.effective_to_date=DATE_SUB(l.effective_from_date,INTERVAL 1 DAY),d.is_current=0 WHERE d.source_attribute_hash<>l.source_attribute_hash;
INSERT IGNORE INTO dw.dim_agent(agent_natural_key,agent_name,agency_name,agent_phone_masked,is_phone_plausible,effective_from_date,source_attribute_hash)
SELECT l.agent_natural_key,l.agent_name_clean,l.agency_name_clean,l.agent_phone_masked,l.is_phone_plausible,l.effective_from_date,l.source_attribute_hash FROM tmp_latest_agent l LEFT JOIN dw.dim_agent d ON d.agent_natural_key=l.agent_natural_key AND d.is_current=1 WHERE d.agent_key IS NULL;
