DROP TABLE IF EXISTS mart.monthly_market_summary;
CREATE TABLE mart.monthly_market_summary AS
WITH ranked AS (SELECT d.month_start_date sale_month,g.state_code,p.property_type_code,f.sale_price_aud,f.days_on_market,f.gross_rental_yield_pct,f.quality_score,ROW_NUMBER() OVER(PARTITION BY d.month_start_date,g.state_code,p.property_type_code ORDER BY f.sale_price_aud) rn_price,ROW_NUMBER() OVER(PARTITION BY d.month_start_date,g.state_code,p.property_type_code ORDER BY f.days_on_market) rn_dom,COUNT(*) OVER(PARTITION BY d.month_start_date,g.state_code,p.property_type_code) cnt FROM dw.fact_property_sale f JOIN dw.dim_date d ON d.date_key=f.sale_date_key JOIN dw.dim_geography g ON g.geography_key=f.geography_key JOIN dw.dim_property_type p ON p.property_type_key=f.property_type_key),
base AS (SELECT sale_month,state_code,property_type_code,MAX(cnt) sale_count,AVG(CASE WHEN rn_price IN(FLOOR((cnt+1)/2),FLOOR((cnt+2)/2)) THEN sale_price_aud END) median_sale_price_aud,AVG(sale_price_aud) average_sale_price_aud,AVG(CASE WHEN rn_dom IN(FLOOR((cnt+1)/2),FLOOR((cnt+2)/2)) THEN days_on_market END) median_days_on_market,AVG(gross_rental_yield_pct) average_gross_rental_yield_pct,AVG(quality_score) average_quality_score FROM ranked GROUP BY sale_month,state_code,property_type_code),
metrics AS (SELECT b.*,LAG(median_sale_price_aud) OVER(PARTITION BY state_code,property_type_code ORDER BY sale_month) prior_month_median_price,AVG(median_sale_price_aud) OVER(PARTITION BY state_code,property_type_code ORDER BY sale_month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) rolling_3m_median_price_aud,SUM(sale_count) OVER(PARTITION BY state_code,property_type_code ORDER BY sale_month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) rolling_3m_sales FROM base b)
SELECT *,IF(prior_month_median_price>0,ROUND((median_sale_price_aud-prior_month_median_price)/prior_month_median_price*100,2),NULL) mom_median_price_change_pct FROM metrics;
ALTER TABLE mart.monthly_market_summary ADD PRIMARY KEY(sale_month,state_code,property_type_code);
DROP TABLE IF EXISTS mart.segment_performance;
CREATE TABLE mart.segment_performance AS SELECT d.month_start_date sale_month,g.state_code,CASE WHEN f.bedrooms IS NULL THEN 'unknown' WHEN f.bedrooms<=2 THEN '0-2' WHEN f.bedrooms=3 THEN '3' WHEN f.bedrooms=4 THEN '4' ELSE '5+' END bedroom_segment,CASE WHEN f.sale_price_aud<500000 THEN 'under_500k' WHEN f.sale_price_aud<1000000 THEN '500k_to_999k' WHEN f.sale_price_aud<2000000 THEN '1m_to_1_999m' ELSE '2m_plus' END price_band,COUNT(*) sale_count,AVG(f.sale_price_aud) average_sale_price_aud,AVG(f.days_on_market) average_days_on_market,AVG(f.days_on_market<=30) sold_within_30_days_rate,AVG(f.price_to_suburb_median_ratio>1) above_suburb_median_rate FROM dw.fact_property_sale f JOIN dw.dim_date d ON d.date_key=f.sale_date_key JOIN dw.dim_geography g ON g.geography_key=f.geography_key GROUP BY 1,2,3,4;
ALTER TABLE mart.segment_performance ADD PRIMARY KEY(sale_month,state_code,bedroom_segment,price_band);
DROP TABLE IF EXISTS mart.data_quality_summary;
CREATE TABLE mart.data_quality_summary AS SELECT batch_id,record_disposition,duplicate_class,COUNT(*) row_count,AVG(quality_score) average_quality_score,SUM(issue_missing_listing_id+issue_invalid_sale_date+issue_invalid_sale_price+issue_invalid_state) critical_issue_count,AVG(issue_postcode_state_mismatch) postcode_state_issue_rate,AVG(issue_invalid_year_built) invalid_year_issue_rate FROM stg.housing_ranked GROUP BY 1,2,3;
ALTER TABLE mart.data_quality_summary ADD PRIMARY KEY(batch_id,record_disposition,duplicate_class);
